---

- name: install packages
  yum: pkg={{ item }} state=present
  with_items:
    - GeoIP

- name: copy config
  template:
    src=GeoIP.conf.j2
    dest=/etc/GeoIP.conf
    backup=yes
  notify: run geoipupdate

- name: setup geoipupdate cron
  template:
    src=geoipupdate.j2
    dest=/etc/cron.weekly/geoipupdate
    mode=0755
    backup=no
